# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: ①②③
author: Gustavo Madeira Santana
description: random thoughts [❤][☃]
twitter_username: gumadeiras
instagram_username: gumadeiras
lastfm_username: gumadeiras
github_username: gumadeiras

# minima:
#   date_format: "%b %-d, %Y"

#   # generate social links in footer
#   social_links:
#     twitter: gumadeiras
#     instagram: gumadeiras
#     lastfm:
#     github: gumadeiras
#     rss: rss
    
# Set this to true to get LaTeX math equation support
use_math: true

# Everything below here can be ignored, unless you want to change the theme entirely
# theme: minima
remote_theme: "mmistakes/jekyll-theme-basically-basic"
skin: night

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
