site: Gustavo Madeira Santana
url: "https://gumadeiras.com"
title: Gustavo Madeira Santana
description: researcher. computer engineer. neuroscientist.
twitter:
  username: gumadeiras
  card: summary_large_image
  creator: gumadeiras
author:
  twitter: gumadeiras
  name: Gustavo Madeira Santana
  avatar: /assets/images/me.jpg
  url: https://gumadeiras.com
permalink: pretty

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache
  - script
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - .ruby-version

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
